import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import FilesCard from "./components/FilesCard";

import { sidebarItems } from "./sidebar";
import { FileFolder } from "./types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body>
        <Navbar title="FileSyncer" />
        <Sidebar
          items={sidebarItems}
          storage={{ total: 20, used: 5 }}
          activeItem="Home"
        />
        <div className="p-4 sm:ml-64">
          <div className="mt-14"></div>
          <FilesCard title="Quick Access" files={recentFiles} />
          <FilesCard title="Recent Files" files={recentFiles} />
          
        </div>
      </body>
    </html>
  );
}

const recentFiles: FileFolder[] = [
  {
    fileID: "home/Education",
    name: "Education",
    type: "folder",
    extension: "",
    size: 0,
    modifiedAt: "2021-09-01",
  },
  {
    fileID: "home/Work",
    name: "Work",
    type: "folder",
    extension: "",
    size: 0,
    modifiedAt: "2021-09-01",
  },
  {
    fileID: "home/welcome.txt",
    name: "welcome",
    type: "file",
    extension: "txt",
    size: 1024,
    modifiedAt: "2021-09-01",
  },
  {
    fileID: "home/hello.pdf",
    name: "hello",
    type: "file",
    extension: "pdf",
    size: 1024,
    modifiedAt: "2021-09-01",
  },
];
